Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
